apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.defaultLabel }}-pv
  namespace: {{ .Values.defaultNamespace }}
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
