apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.defaultLabel }}-pvc
  namespace: {{ .Values.defaultNamespace }} 
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1G
