# Default values for chatgpt-frontend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
defaultLabel: chatgpt-frontend

image:
  repository: uj5ghare/chatgpt-frontend
  pullPolicy: Always
  tag: "1.37.1"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  className: nginx
  host: chatgpt-frontend.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
