apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatgpt-backend-pv
  namespace: chatgpt
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
