apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatgpt-backend-pvc
  namespace: chatgpt
spec: 
  accessModes:  
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1G
